// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 15.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace AWSToolkitUITests
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UITesting.WpfControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public partial class UIMap
    {
        #region Properties
        public UIAWSStudioWindow UIAWSStudioWindow
        {
            get
            {
                if ((this.mUIAWSStudioWindow == null))
                {
                    this.mUIAWSStudioWindow = new UIAWSStudioWindow();
                }
                return this.mUIAWSStudioWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIAWSStudioWindow mUIAWSStudioWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIAWSStudioWindow : WinWindow
    {
        
        public UIAWSStudioWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "AWS Studio";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("AWS Studio");
            #endregion
        }
        
        #region Properties
        public WinTitleBar UIAWSStudioTitleBar
        {
            get
            {
                if ((this.mUIAWSStudioTitleBar == null))
                {
                    this.mUIAWSStudioTitleBar = new WinTitleBar(this);
                    #region Search Criteria
                    this.mUIAWSStudioTitleBar.WindowTitles.Add("AWS Studio");
                    #endregion
                }
                return this.mUIAWSStudioTitleBar;
            }
        }

        public UIAWSExplorerCustom UIAWSExplorerCustom
        {
            get
            {
                if ((this.mUIAWSExplorerCustom == null))
                {
                    this.mUIAWSExplorerCustom = new UIAWSExplorerCustom(this);
                }
                return this.mUIAWSExplorerCustom;
            }
        }
        #endregion

        #region Fields
        private WinTitleBar mUIAWSStudioTitleBar;
        private UIAWSExplorerCustom mUIAWSExplorerCustom;
        #endregion
    }

    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIAWSExplorerCustom : WpfCustom
    {
        
        public UIAWSExplorerCustom(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfControl.PropertyNames.ClassName] = "Uia.NavigatorControl";
            this.SearchProperties[WpfControl.PropertyNames.AutomationId] = "AWSExplorer";
            this.WindowTitles.Add("AWS Studio");
            #endregion
        }
        
        #region Properties
        public WpfTree UIResourceTreeTree
        {
            get
            {
                if ((this.mUIResourceTreeTree == null))
                {
                    this.mUIResourceTreeTree = new WpfTree(this);
                    #region Search Criteria
                    this.mUIResourceTreeTree.SearchProperties[WpfTree.PropertyNames.AutomationId] = "ResourceTree";
                    this.mUIResourceTreeTree.WindowTitles.Add("AWS Studio");
                    #endregion
                }
                return this.mUIResourceTreeTree;
            }
        }
        
        public WpfComboBox UIRegionsPickerComboBox
        {
            get
            {
                if ((this.mUIRegionsPickerComboBox == null))
                {
                    this.mUIRegionsPickerComboBox = new WpfComboBox(this);
                    #region Search Criteria
                    this.mUIRegionsPickerComboBox.SearchProperties[WpfComboBox.PropertyNames.AutomationId] = "RegionsPicker";
                    this.mUIRegionsPickerComboBox.WindowTitles.Add("AWS Studio");
                    #endregion
                }
                return this.mUIRegionsPickerComboBox;
            }
        }
        
        public UIRegisteredProfilesPiCustom UIRegisteredProfilesPiCustom
        {
            get
            {
                if ((this.mUIRegisteredProfilesPiCustom == null))
                {
                    this.mUIRegisteredProfilesPiCustom = new UIRegisteredProfilesPiCustom(this);
                }
                return this.mUIRegisteredProfilesPiCustom;
            }
        }
        #endregion
        
        #region Fields
        private WpfTree mUIResourceTreeTree;
        
        private WpfComboBox mUIRegionsPickerComboBox;
        
        private UIRegisteredProfilesPiCustom mUIRegisteredProfilesPiCustom;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIRegisteredProfilesPiCustom : WpfCustom
    {
        
        public UIRegisteredProfilesPiCustom(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfControl.PropertyNames.ClassName] = "Uia.RegisteredProfilesPicker";
            this.SearchProperties[WpfControl.PropertyNames.AutomationId] = "RegisteredProfilesPicker";
            this.WindowTitles.Add("AWS Studio");
            #endregion
        }
        
        #region Properties
        public WpfComboBox UI_ctlComboComboBox
        {
            get
            {
                if ((this.mUI_ctlComboComboBox == null))
                {
                    this.mUI_ctlComboComboBox = new WpfComboBox(this);
                    #region Search Criteria
                    this.mUI_ctlComboComboBox.SearchProperties[WpfComboBox.PropertyNames.AutomationId] = "_ctlCombo";
                    this.mUI_ctlComboComboBox.WindowTitles.Add("AWS Studio");
                    #endregion
                }
                return this.mUI_ctlComboComboBox;
            }
        }
        #endregion
        
        #region Fields
        private WpfComboBox mUI_ctlComboComboBox;
        #endregion
    }
}
