name: CI

on:
    push:
        branches: [main, release/stable]
    pull_request:
        branches: [main, feature/*, release/*]

jobs:
    build:
        strategy:
            matrix:
                vs: [2019, 2022]
                configuration: [Debug, Release]
                include:
                  - vs: 2019
                    name: VS 2019
                    os: windows-2019
                    vs-version: "[16.0,17.0)"
                  - vs: 2022
                    name: VS 2022
                    os: windows-2022
                    vs-version: "[17.0,18.0)"

        name: ${{ matrix.name }} (${{ matrix.configuration }})
        runs-on: ${{ matrix.os }}
        env:
            TEST_REPORT_HTML: TestResults/toolkit-test-results.html

        steps:
            - uses: actions/checkout@v3
            - name: Add msbuild to PATH
              uses: microsoft/setup-msbuild@v1.1
              with:
                  vs-version: ${{ matrix.vs-version }}

            - name: Restore
              run: msbuild buildtools\build.proj /t:restore /p:Configuration=${{ matrix.configuration }}

            # TODO_ENABLE_BEFORE_CAWS_RELEASE
            #- name: Verify
            #  run: msbuild buildtools\build.proj /t:verify

            - name: Compile
              # DeployExtension=false skips installing the extension into an experimental instance of VS (we aren't going to debug it on CI machine)
              # This increases build time dramatically and prevents cryptic DEVENV warning spam.
              run: msbuild buildtools\build.proj /t:compile /p:DeployExtension=false /p:Configuration=${{ matrix.configuration }}

            - name: Test
              run: msbuild buildtools\build.proj /t:test /p:Configuration=${{ matrix.configuration }}

            - name: Attach Test Report as Build Artifact
              if: always()
              uses: actions/upload-artifact@v3
              with:
                  name: test-reports-${{ matrix.vs }}-${{ matrix.configuration }}
                  path: ${{ env.TEST_REPORT_HTML }}
