name: CI

on:
    push:
        branches: [master]
    pull_request:
        branches: [master, feature/*]

jobs:
    build:
        runs-on: windows-2016
        env:
            TEST_REPORT_HTML: TestResults/toolkit-test-results.html

        steps:
            - uses: actions/checkout@v2
            - name: Add msbuild to PATH
              uses: microsoft/setup-msbuild@v1.0.2
              with:
                  vs-version: "[15.0,16.0)"

            - name: Remove v16 Team Explorer project
              run: |
                  [xml]$xml = Get-Content .\vspackages\manifests\15.0\source.extension.vsixmanifest
                  $ns = New-Object System.Xml.XmlNamespaceManager($xml.NameTable)
                  $ns.AddNamespace("ns", $xml.DocumentElement.NamespaceURI)
                  $ns.AddNamespace("d", "http://schemas.microsoft.com/developer/vsx-schema-design/2011")
                  $node = $xml.SelectSingleNode("//ns:PackageManifest/ns:Assets/ns:Asset[@d:ProjectName='AWSToolkit.CodeCommitTeamExplorer.v16']", $ns)
                  $node.ParentNode.RemoveChild($node)
                  $xml.save("$pwd\vspackages\manifests\15.0\source.extension.vsixmanifest")
                  dotnet sln solutions\AWSVisualStudioToolkit.sln remove vspackages\AWSToolkit.CodeCommitTeamExplorer.v16\AWSToolkit.CodeCommitTeamExplorer.v16.csproj
                  dotnet remove vspackages\AWSToolkitPackage\AWSToolkitPackage.csproj reference "`$(BuildRoot)\vspackages\AWSToolkit.CodeCommitTeamExplorer.v16\AWSToolkit.CodeCommitTeamExplorer.v16.csproj"

            - name: Remove v15 Team Explorer project
              run: |
                  [xml]$xml = Get-Content .\vspackages\manifests\15.0\source.extension.vsixmanifest
                  $ns = New-Object System.Xml.XmlNamespaceManager($xml.NameTable)
                  $ns.AddNamespace("ns", $xml.DocumentElement.NamespaceURI)
                  $ns.AddNamespace("d", "http://schemas.microsoft.com/developer/vsx-schema-design/2011")
                  $node = $xml.SelectSingleNode("//ns:PackageManifest/ns:Assets/ns:Asset[@d:ProjectName='AWSToolkit.CodeCommitTeamExplorer.v15']", $ns)
                  $node.ParentNode.RemoveChild($node)
                  $xml.save("$pwd\vspackages\manifests\15.0\source.extension.vsixmanifest")
                  dotnet sln solutions\AWSVisualStudioToolkit.sln remove vspackages\AWSToolkit.CodeCommitTeamExplorer.v15\AWSToolkit.CodeCommitTeamExplorer.v15.csproj
                  dotnet remove vspackages\AWSToolkitPackage\AWSToolkitPackage.csproj reference "`$(BuildRoot)\vspackages\AWSToolkit.CodeCommitTeamExplorer.v15\AWSToolkit.CodeCommitTeamExplorer.v15.csproj"

            - name: Restore
              run: msbuild buildtools\build.proj /t:restore

            - name: Compile
              run: msbuild buildtools\build.proj /t:compile

            - name: Test
              run: msbuild buildtools\build.proj /t:test

            - name: Attach Test Report as Build Artifact
              if: always()
              uses: actions/upload-artifact@v2
              with:
                  name: test-reports
                  path: ${{ env.TEST_REPORT_HTML }}
